export const journeysResponse = {
	data: {
		journeys: [
			{
				type: 'journey',
				legs: [
					{
						origin: {
							type: 'stop',
							id: '8000261',
							name: 'München Hbf',
							location: {
								type: 'location',
								id: '8000261',
								latitude: 48.140364,
								longitude: 11.558744,
							},
							products: {
								nationalExpress: true,
								national: true,
								regionalExp: true,
								regional: true,
								suburban: true,
								bus: true,
								ferry: false,
								subway: true,
								tram: true,
								taxi: false,
							},
						},
						destination: {
							type: 'stop',
							id: '8000284',
							name: 'Nürnberg Hbf',
							location: {
								type: 'location',
								id: '8000284',
								latitude: 49.445435,
								longitude: 11.08227,
							},
							products: {
								nationalExpress: true,
								national: true,
								regionalExp: true,
								regional: true,
								suburban: true,
								bus: true,
								ferry: false,
								subway: true,
								tram: true,
								taxi: false,
							},
						},
						departure: '2022-12-09T05:11:00+01:00',
						plannedDeparture: '2022-12-09T05:11:00+01:00',
						departureDelay: 0,
						arrival: '2022-12-09T06:29:00+01:00',
						plannedArrival: '2022-12-09T06:29:00+01:00',
						arrivalDelay: 0,
						reachable: true,
						tripId: '1|164467|0|80|9122022',
						line: {
							type: 'line',
							id: 'ice-886',
							fahrtNr: '886',
							name: 'ICE 886',
							public: true,
							adminCode: '80____',
							productName: 'ICE',
							mode: 'train',
							product: 'nationalExpress',
							operator: {
								type: 'operator',
								id: 'db-fernverkehr-ag',
								name: 'DB Fernverkehr AG',
							},
						},
						direction: 'Hamburg-Altona',
						currentLocation: {
							type: 'location',
							latitude: 48.144867,
							longitude: 11.504548,
						},
						arrivalPlatform: '7',
						plannedArrivalPlatform: '7',
						arrivalPrognosisType: 'prognosed',
						departurePlatform: '19',
						plannedDeparturePlatform: '19',
						departurePrognosisType: 'prognosed',
						stopovers: [
							{
								stop: {
									type: 'stop',
									id: '8000261',
									name: 'München Hbf',
									location: {
										type: 'location',
										id: '8000261',
										latitude: 48.140364,
										longitude: 11.558744,
									},
									products: {
										nationalExpress: true,
										national: true,
										regionalExp: true,
										regional: true,
										suburban: true,
										bus: true,
										ferry: false,
										subway: true,
										tram: true,
										taxi: false,
									},
								},
								arrival: null,
								plannedArrival: null,
								arrivalDelay: null,
								arrivalPlatform: null,
								arrivalPrognosisType: null,
								plannedArrivalPlatform: null,
								departure: '2022-12-09T05:11:00+01:00',
								plannedDeparture: '2022-12-09T05:11:00+01:00',
								departureDelay: 0,
								departurePlatform: '19',
								departurePrognosisType: 'prognosed',
								plannedDeparturePlatform: '19',
							},
							{
								stop: {
									type: 'stop',
									id: '8000183',
									name: 'Ingolstadt Hbf',
									location: {
										type: 'location',
										id: '8000183',
										latitude: 48.744538,
										longitude: 11.437335,
									},
									products: {
										nationalExpress: true,
										national: false,
										regionalExp: true,
										regional: true,
										suburban: false,
										bus: true,
										ferry: false,
										subway: false,
										tram: false,
										taxi: false,
									},
								},
								arrival: '2022-12-09T05:53:00+01:00',
								plannedArrival: '2022-12-09T05:53:00+01:00',
								arrivalDelay: 0,
								arrivalPlatform: '4',
								arrivalPrognosisType: 'prognosed',
								plannedArrivalPlatform: '4',
								departure: '2022-12-09T05:57:00+01:00',
								plannedDeparture: '2022-12-09T05:57:00+01:00',
								departureDelay: 0,
								departurePlatform: '4',
								departurePrognosisType: 'prognosed',
								plannedDeparturePlatform: '4',
							},
							{
								stop: {
									type: 'stop',
									id: '8000284',
									name: 'Nürnberg Hbf',
									location: {
										type: 'location',
										id: '8000284',
										latitude: 49.445435,
										longitude: 11.08227,
									},
									products: {
										nationalExpress: true,
										national: true,
										regionalExp: true,
										regional: true,
										suburban: true,
										bus: true,
										ferry: false,
										subway: true,
										tram: true,
										taxi: false,
									},
								},
								arrival: '2022-12-09T06:29:00+01:00',
								plannedArrival: '2022-12-09T06:29:00+01:00',
								arrivalDelay: 0,
								arrivalPlatform: '7',
								arrivalPrognosisType: 'prognosed',
								plannedArrivalPlatform: '7',
								departure: null,
								plannedDeparture: null,
								departureDelay: null,
								departurePlatform: null,
								departurePrognosisType: null,
								plannedDeparturePlatform: null,
							},
						],
						remarks: [
							{
								text: 'Komfort Check-in possible (visit bahn.de/kci for more information)',
								type: 'hint',
								code: 'komfort-checkin',
								summary: 'Komfort-Checkin available',
							},
							{
								type: 'hint',
								code: 'PM',
								text: 'Please wear an FFP2 mask. You are legally required to do so',
							},
							{
								text: 'Bicycles conveyed - subject to reservation',
								type: 'hint',
								code: 'bicycle-conveyance-reservation',
								summary: 'bicycles conveyed, subject to reservation',
							},
							{
								text: 'Number of bicycles conveyed limited',
								type: 'hint',
								code: 'bicycle-conveyance',
								summary: 'bicycles conveyed',
							},
							{
								text: 'Bordrestaurant',
								type: 'hint',
								code: 'on-board-restaurant',
								summary: 'Bordrestaurant available',
							},
							{
								text: 'vehicle-mounted access aid',
								type: 'hint',
								code: 'boarding-ramp',
								summary: 'vehicle-mounted boarding ramp available',
							},
							{
								type: 'status',
								summary: 'ICE 886: Ingolstadt Hbf->Nürnberg Hbf: Information.',
								code: null,
								text: 'No vehicle-carried boarding aid. If a change in booking is required for travellers with reduced mobility, our Mobility Service Centre can be reached at +49 30 65212888.',
							},
						],
						loadFactor: 'low-to-medium',
					},
					{
						origin: {
							type: 'stop',
							id: '8000284',
							name: 'Nürnberg Hbf',
							location: {
								type: 'location',
								id: '8000284',
								latitude: 49.445435,
								longitude: 11.08227,
							},
							products: {
								nationalExpress: true,
								national: true,
								regionalExp: true,
								regional: true,
								suburban: true,
								bus: true,
								ferry: false,
								subway: true,
								tram: true,
								taxi: false,
							},
						},
						destination: {
							type: 'stop',
							id: '8098160',
							name: 'Berlin Hbf (tief)',
							location: {
								type: 'location',
								id: '8098160',
								latitude: 52.52585,
								longitude: 13.368892,
							},
							products: {
								nationalExpress: true,
								national: true,
								regionalExp: true,
								regional: true,
								suburban: true,
								bus: true,
								ferry: false,
								subway: true,
								tram: true,
								taxi: false,
							},
							station: {
								type: 'station',
								id: '8011160',
								name: 'Berlin Hbf',
								location: {
									type: 'location',
									id: '8011160',
									latitude: 52.524924,
									longitude: 13.369629,
								},
								products: {
									nationalExpress: true,
									national: true,
									regionalExp: true,
									regional: true,
									suburban: true,
									bus: true,
									ferry: false,
									subway: true,
									tram: true,
									taxi: false,
								},
							},
						},
						departure: '2022-12-09T07:05:00+01:00',
						plannedDeparture: '2022-12-09T07:05:00+01:00',
						departureDelay: 0,
						arrival: '2022-12-09T10:25:00+01:00',
						plannedArrival: '2022-12-09T10:25:00+01:00',
						arrivalDelay: 0,
						reachable: true,
						tripId: '1|163382|0|80|9122022',
						line: {
							type: 'line',
							id: 'ice-804',
							fahrtNr: '804',
							name: 'ICE 804',
							public: true,
							adminCode: '80____',
							productName: 'ICE',
							mode: 'train',
							product: 'nationalExpress',
							operator: {
								type: 'operator',
								id: 'db-fernverkehr-ag',
								name: 'DB Fernverkehr AG',
							},
						},
						direction: 'Berlin Hbf',
						currentLocation: {
							type: 'location',
							latitude: 48.150117,
							longitude: 11.461687,
						},
						arrivalPlatform: '7',
						plannedArrivalPlatform: '7',
						arrivalPrognosisType: 'prognosed',
						departurePlatform: '7',
						plannedDeparturePlatform: '7',
						departurePrognosisType: 'prognosed',
						stopovers: [
							{
								stop: {
									type: 'stop',
									id: '8000284',
									name: 'Nürnberg Hbf',
									location: {
										type: 'location',
										id: '8000284',
										latitude: 49.445435,
										longitude: 11.08227,
									},
									products: {
										nationalExpress: true,
										national: true,
										regionalExp: true,
										regional: true,
										suburban: true,
										bus: true,
										ferry: false,
										subway: true,
										tram: true,
										taxi: false,
									},
								},
								arrival: null,
								plannedArrival: null,
								arrivalDelay: null,
								arrivalPlatform: null,
								arrivalPrognosisType: null,
								plannedArrivalPlatform: null,
								departure: '2022-12-09T07:05:00+01:00',
								plannedDeparture: '2022-12-09T07:05:00+01:00',
								departureDelay: 0,
								departurePlatform: '7',
								departurePrognosisType: 'prognosed',
								plannedDeparturePlatform: '7',
								remarks: [
									{
										type: 'hint',
										code: 'text.journeystop.product.or.direction.changes.stop.message',
										text: 'As ICE 804 heading towards Berlin Hbf from here',
									},
								],
							},
							{
								stop: {
									type: 'stop',
									id: '8000025',
									name: 'Bamberg',
									location: {
										type: 'location',
										id: '8000025',
										latitude: 49.900793,
										longitude: 10.899493,
									},
									products: {
										nationalExpress: true,
										national: true,
										regionalExp: false,
										regional: true,
										suburban: true,
										bus: true,
										ferry: false,
										subway: false,
										tram: false,
										taxi: true,
									},
								},
								arrival: '2022-12-09T07:39:00+01:00',
								plannedArrival: '2022-12-09T07:39:00+01:00',
								arrivalDelay: 0,
								arrivalPlatform: '6',
								arrivalPrognosisType: 'prognosed',
								plannedArrivalPlatform: '6',
								departure: '2022-12-09T07:41:00+01:00',
								plannedDeparture: '2022-12-09T07:41:00+01:00',
								departureDelay: 0,
								departurePlatform: '6',
								departurePrognosisType: 'prognosed',
								plannedDeparturePlatform: '6',
								remarks: [
									{
										type: 'hint',
										code: 'text.journeystop.product.or.direction.changes.stop.message',
										text: 'As ICE 804 heading towards Kiel Hbf from here',
									},
								],
							},
							{
								stop: {
									type: 'stop',
									id: '8010101',
									name: 'Erfurt Hbf',
									location: {
										type: 'location',
										id: '8010101',
										latitude: 50.97255,
										longitude: 11.038502,
									},
									products: {
										nationalExpress: true,
										national: true,
										regionalExp: true,
										regional: true,
										suburban: false,
										bus: true,
										ferry: false,
										subway: false,
										tram: true,
										taxi: false,
									},
								},
								arrival: '2022-12-09T08:24:00+01:00',
								plannedArrival: '2022-12-09T08:24:00+01:00',
								arrivalDelay: 0,
								arrivalPlatform: '9',
								arrivalPrognosisType: 'prognosed',
								plannedArrivalPlatform: '9',
								departure: '2022-12-09T08:32:00+01:00',
								plannedDeparture: '2022-12-09T08:32:00+01:00',
								departureDelay: 0,
								departurePlatform: '9',
								departurePrognosisType: 'prognosed',
								plannedDeparturePlatform: '9',
							},
							{
								stop: {
									type: 'stop',
									id: '8010159',
									name: 'Halle(Saale)Hbf',
									location: {
										type: 'location',
										id: '8010159',
										latitude: 51.477079,
										longitude: 11.98699,
									},
									products: {
										nationalExpress: true,
										national: true,
										regionalExp: true,
										regional: true,
										suburban: true,
										bus: true,
										ferry: false,
										subway: false,
										tram: true,
										taxi: true,
									},
								},
								arrival: '2022-12-09T09:04:00+01:00',
								plannedArrival: '2022-12-09T09:04:00+01:00',
								arrivalDelay: 0,
								arrivalPlatform: '8',
								arrivalPrognosisType: 'prognosed',
								plannedArrivalPlatform: '8',
								departure: '2022-12-09T09:06:00+01:00',
								plannedDeparture: '2022-12-09T09:06:00+01:00',
								departureDelay: 0,
								departurePlatform: '8',
								departurePrognosisType: 'prognosed',
								plannedDeparturePlatform: '8',
							},
							{
								stop: {
									type: 'stop',
									id: '8010050',
									name: 'Bitterfeld',
									location: {
										type: 'location',
										id: '8010050',
										latitude: 51.622911,
										longitude: 12.316966,
									},
									products: {
										nationalExpress: true,
										national: true,
										regionalExp: false,
										regional: true,
										suburban: true,
										bus: true,
										ferry: false,
										subway: false,
										tram: false,
										taxi: true,
									},
								},
								arrival: '2022-12-09T09:24:00+01:00',
								plannedArrival: '2022-12-09T09:24:00+01:00',
								arrivalDelay: 0,
								arrivalPlatform: '2',
								arrivalPrognosisType: 'prognosed',
								plannedArrivalPlatform: '2',
								departure: '2022-12-09T09:25:00+01:00',
								plannedDeparture: '2022-12-09T09:25:00+01:00',
								departureDelay: 0,
								departurePlatform: '2',
								departurePrognosisType: 'prognosed',
								plannedDeparturePlatform: '2',
							},
							{
								stop: {
									type: 'stop',
									id: '8011113',
									name: 'Berlin Südkreuz',
									location: {
										type: 'location',
										id: '8011113',
										latitude: 52.47623,
										longitude: 13.365863,
									},
									products: {
										nationalExpress: true,
										national: true,
										regionalExp: true,
										regional: true,
										suburban: true,
										bus: true,
										ferry: false,
										subway: false,
										tram: false,
										taxi: false,
									},
								},
								arrival: '2022-12-09T10:17:00+01:00',
								plannedArrival: '2022-12-09T10:17:00+01:00',
								arrivalDelay: 0,
								arrivalPlatform: '8',
								arrivalPrognosisType: 'prognosed',
								plannedArrivalPlatform: '8',
								departure: '2022-12-09T10:19:00+01:00',
								plannedDeparture: '2022-12-09T10:19:00+01:00',
								departureDelay: 0,
								departurePlatform: '8',
								departurePrognosisType: 'prognosed',
								plannedDeparturePlatform: '8',
							},
							{
								stop: {
									type: 'stop',
									id: '8098160',
									name: 'Berlin Hbf (tief)',
									location: {
										type: 'location',
										id: '8098160',
										latitude: 52.52585,
										longitude: 13.368892,
									},
									products: {
										nationalExpress: true,
										national: true,
										regionalExp: true,
										regional: true,
										suburban: true,
										bus: true,
										ferry: false,
										subway: true,
										tram: true,
										taxi: false,
									},
									station: {
										type: 'station',
										id: '8011160',
										name: 'Berlin Hbf',
										location: {
											type: 'location',
											id: '8011160',
											latitude: 52.524924,
											longitude: 13.369629,
										},
										products: {
											nationalExpress: true,
											national: true,
											regionalExp: true,
											regional: true,
											suburban: true,
											bus: true,
											ferry: false,
											subway: true,
											tram: true,
											taxi: false,
										},
									},
								},
								arrival: '2022-12-09T10:25:00+01:00',
								plannedArrival: '2022-12-09T10:25:00+01:00',
								arrivalDelay: 0,
								arrivalPlatform: '7',
								arrivalPrognosisType: 'prognosed',
								plannedArrivalPlatform: '7',
								departure: null,
								plannedDeparture: null,
								departureDelay: null,
								departurePlatform: null,
								departurePrognosisType: null,
								plannedDeparturePlatform: null,
							},
						],
						remarks: [
							{
								text: 'Komfort Check-in possible (visit bahn.de/kci for more information)',
								type: 'hint',
								code: 'komfort-checkin',
								summary: 'Komfort-Checkin available',
							},
							{
								type: 'hint',
								code: 'PM',
								text: 'Please wear an FFP2 mask. You are legally required to do so',
							},
							{
								text: 'Bicycles conveyed - subject to reservation',
								type: 'hint',
								code: 'bicycle-conveyance-reservation',
								summary: 'bicycles conveyed, subject to reservation',
							},
							{
								text: 'Number of bicycles conveyed limited',
								type: 'hint',
								code: 'bicycle-conveyance',
								summary: 'bicycles conveyed',
							},
							{
								text: 'Bordrestaurant',
								type: 'hint',
								code: 'on-board-restaurant',
								summary: 'Bordrestaurant available',
							},
							{
								text: 'vehicle-mounted access aid',
								type: 'hint',
								code: 'boarding-ramp',
								summary: 'vehicle-mounted boarding ramp available',
							},
							{
								type: 'hint',
								code: 'text.journeystop.product.or.direction.changes.journey.message',
								text: 'From Bamberg as ICE 804 heading towards Kiel Hbf',
							},
						],
						loadFactor: 'high',
					},
				],
				refreshToken:
					'T$A=1@O=München Hbf@L=8000261@a=128@$A=1@O=Nürnberg Hbf@L=8000284@a=128@$202212090511$202212090629$ICE  886$FB$1$$$$$$§T$A=1@O=Nürnberg Hbf@L=8000284@a=128@$A=1@O=Berlin Hbf (tief)@L=8098160@a=128@$202212090705$202212091025$ICE  804$FB$1$$$$$$',

				price: {
					amount: 168,
					currency: 'EUR',
					hint: null,
				},
			},
		],
	},
};

export const locationResponse = {
	data: [
		{
			type: 'stop',
			id: '8000261',
			name: 'Munich',
			location: {
				type: 'location',
				id: '8000261',
				latitude: 48.140364,
				longitude: 11.558744,
			},
		},
		{
			type: 'stop',
			id: '8011160',
			name: 'Berlin Hbf',
			location: {
				type: 'location',
				id: '8011160',
				latitude: 52.524924,
				longitude: 13.369629,
			},
		},
	],
};
